name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
      
    steps:
    - name: Set timezone
      run: Set-TimeZone -Id "China Standard Time"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild KeqingNiuza.sln /t:Restore /p:Configuration=Release

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Build the application
      run: msbuild KeqingNiuza.sln /p:Configuration=Release
        
    - name: Create publish files
      shell: cmd
      run: '".\bin\Release\KeqingNiuza Launcher.exe" --deploy'
        
    - name: Deploy to cdn2 brunch
      # You may pin to the exact commit or the version.
      # uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        # Set a generated GITHUB_TOKEN for pushing to the remote branch.
        github_token: ${{secrets.DEPLOY_TOKEN}}
        # Set a target branch for deployment.
        publish_branch: cdn2
        # Set an input directory for deployment.
        publish_dir: bin/Release/cdn2
        # An alias for enable_jekyll to disable adding .nojekyll file to master or gh-pages branches
        disable_nojekyll: true

    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      
    - name: Setup Tencent COSCMD
      run: pip install coscmd

    - name: Deploy to qcloud
      shell: cmd
      run: |
        coscmd config -a ${{secrets.QCLOUD_SECRET_ID}} -s ${{ secrets.QCLOUD_SECRET_KEY }} -b ${{ secrets.QCLOUD_COS_BUCKET }} -r ${{secrets.QCLOUD_COS_REGION}}
        coscmd upload -r bin/Release/cdn2/meta keqingniuza/meta
